AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
Rails/Date:
  Exclude:
    - 'lib/**/*'
Style/IndentArray:
  EnforcedStyle: consistent
Rails/OutputSafety:
  Enabled: false
